### PR TITLE
Added mobile responsiveness for Support + bug fix

### LINKED ISSUE #95: Mobile Responsive Support Page + Bug Fixing
image

- put the mascot ontop of the donations
- social media icons should also be smaller and mobile responsive

image
- recenter connect with us

### PR DESCRIPTION
**Pull request by tingtingtingtin**
Screenshots
Screenshot 2024-07-23 234642
Screenshot 2024-07-23 234633

Added mobile responsiveness to Support.jsx and centered "Connect with us!" text
Spacing between socials icons might be slightly different for medium display because I changed justify-evenly to justify-center but it should scale better now(?)

### CODE REVIEW

File: src/components/support/Support.jsx [hunk 1]
```diff
@@ -11,9 +11,9 @@ const Support = () => {
     <div className="px-10 bg-biscuits-orange-300">
       <Title text="Support Us" food="croissant" color="gray" />
       <div className="">
-        <div className="flex justify-items-end gap-x-6 py-14 justify-evenly items-center">
+        <div className="md:flex justify-items-end gap-x-6 py-14 justify-evenly items-center">
```
Comment (seanquiambao) [inline src/components/support/Support.jsx]: maybe change the breakpoints to xl rather than md. otherwise looks pretty good
image

**Review by seanquiambao — CHANGES_REQUESTED** [review]

**Comment by seanquiambao** [comment]
wrong pr oops

**Review by seanquiambao — APPROVED** [review]
